// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"users/internal/biz"
	"users/internal/conf"
	"users/internal/data"
	"users/internal/dep"
	"users/internal/server"
	"users/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, bootstrap *conf.Bootstrap, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData, logger)
	usersUsecase := biz.NewUsersUsecase(usersRepo, logger)
	usersService := service.NewUsersService(usersUsecase, logger)
	meterProvider, err := dep.NewMeterProvider(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	meter, err := dep.NewMeter(bootstrap, meterProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	textMapPropagator := dep.NewTextMapPropagator()
	tracerProvider, err := dep.NewTracerProvider(contextContext, bootstrap, textMapPropagator)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(confServer, usersService, logger, meter, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer, err := server.NewHTTPServer(confServer, usersService, logger, meter, tracerProvider)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
